[release.sagitta]
  latest = "1.4.4"

  security_advisory = [
  ]

  notes = "Maintenance release"

[release.equuleus]
  latest = "1.3.8"

  security_advisory = []

  notes = "Unsupported â€” VyOS 1.3 has reached end of life in April 2025."

